### ISSUE TITLE
Image missing from Docker Hub?

### ISSUE THREAD

**Issue by laserpants** [somleng/somleng-scfm#554]
I am following the steps in the installation guide (INSTALLATION.md) but I get the following error when I run `docker-compose up`:

```
ERROR: pull access denied for somleng/somleng-scfm, repository does not exist or may require 'docker login'
```

**Comment by dwilkie** [comment]
Yeah, sorry the installation guide is out of date. We don’t currently use Docker development or [deployment](https://github.com/somleng/somleng-project/blob/master/infrastructure/terraform/somleng.org/eb.tf#L208) of SCFM so the Dockerfile and docker-compose.yml is out of date. You can run SCFM locally by installing Ruby on you dev machine, or you could fix the Dockerfile and Docker-compose to work with Postgres.
