### ISSUE TITLE
Unable to create super user 

### ISSUE THREAD

**Issue by uttamsolanki** [somleng/somleng-scfm#775]
Hi there i have perform all steps given in installation page .but could not create super admin user.
![Screen Shot 2020-03-26 at 1 14 10 AM](https://user-images.githubusercontent.com/9497470/77612727-40236a00-6eff-11ea-85a9-079de655092b.png)
This is my docker file and below my output console

![Screen Shot 2020-03-26 at 1 11 52 AM](https://user-images.githubusercontent.com/9497470/77612583-e58a0e00-6efe-11ea-9767-0da889413653.png)

Moreover, if changing RAILS_ENV=developement and database name  as well in dockerfile at that time its also give below error.Can you please help me to resolve this issue. 

ActiveRecord::EnvironmentMismatchError: You are attempting to modify a database that was last run in `test` environment in docker
    rails db:environment:set RAILS_ENV=development

**Comment by dwilkie** [comment]
Somleng-SCFM has been rewritten.
