### ISSUE TITLE
docker: can't find a suitable configuration file

### ISSUE THREAD

**Issue by chris-amaya** [somleng/somleng-scfm#904]
i'm not been able to install the project due an error with docker. (see below)
![image](https://user-images.githubusercontent.com/24614876/89429458-31e22780-d703-11ea-930f-0bf86c429f60.png)

these are the commands i have run.

```
git clone https://github.com/somleng/somleng-scfm.git
cd somleng-scfm
docker-compose up
```

**Comment by dwilkie** [comment]
This has been rewritten
